config/routes.rb
Rails.application.routes.draw do
  resources :parents
  resources :teachers
  get 'login/login'
  root 'teachers#index'
  get 'login/logout'
  post 'login/login'
end

app/models/parent.rb
class Parent < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def login
    if request.post?
      teacher = Teacher.find_by_email(params[:email])
      if teacher && teacher.authenticate(params[:password])
        session[:teacher_id] = teacher.id
        redirect_to root_path, notice: "Login successful"
      else
        flash.now[:notice] = "Not Logged In"
      end
    end
  end

  def logout
    session[:teacher_id] = nil
    redirect_to login_login_path, notice: "Successfully logged out."
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.all
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render :show, status: :created, location: @parent }
      else
        format.html { render :new }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:name, :student_name, :email, :teacher_id)
    end

    def logged_in?
      if Teacher.find_by_id(session[:teacher_id])
        return true
      else
        redirect_to login_login_path, notice: 'Restricted. Login first.'
      end
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :logged_in?
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teacher = Teacher.all
    @parents = Parent.all.select{|p| p.teacher_id == session[:teacher_id]}
  end

  # GET /teachers/1/edit
  def edit
  end


  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :email, :password, :password_confirmation)
    end

    def logged_in?
      if Teacher.find_by_id(session[:teacher_id])
        return true
      else
        redirect_to login_login_path, notice: 'Restricted. Login first.'
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/_messages.html.erb
 <% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :class => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <%= link_to 'Home', root_path, class: "inline-link-1" %>
  <%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Teacher Book" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Teacher Book" %>">
    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_include_tag 'application'%>
    <%= csrf_meta_tags %>
  </head>
  <% if session[:teacher_id] %>
    <header>
      <h4>Logged in as <%= Teacher.find_by_id(session[:teacher_id]).name %></h4>
    </header>
  <% end %>
  <body align="center">
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <main role="main">
      <%= link_to "Logout", login_logout_path, class: "inline-link-1" if session[:teacher_id] %>
      <%= render 'layouts/messages' %>
      <%= yield %>
    </main>

  </body>
</html>

app/views/login/login.html.erb
<h2>Login</h2>

<%= form_tag do %>
  <%= label_tag :email %>
  <%= text_field_tag :email %>
  <%= label_tag :password %>
  <%= password_field_tag :password %>
  <%= submit_tag "Login" %>
<% end %>

app/views/login/logout.html.erb
<h2>Login#logout</h2>
<p>Find me in app/views/login/logout.html.erb</p>

app/views/parents/_form.html.erb
<%= form_for(@parent) do |f| %>
  <% if @parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% @parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :student_name %><br>
    <%= f.text_field :student_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :teacher_id %><br>
    <%= f.number_field :teacher_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h2>Editing Parent</h2>

<%= render 'form' %>

app/views/parents/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Parents</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Student name</th>
      <th>Email</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.each do |parent| %>
      <tr>
        <td><%= parent.name %></td>
        <td><%= parent.student_name %></td>
        <td><%= parent.email %></td>
        <td><%= parent.teacher_id %></td>
        <td><%= link_to 'Edit', parent_edit_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h2>New Parent</h2>

<%= render 'form' %>

<%= link_to 'Back', parents_path %>

app/views/parents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parent.name %>
</p>

<p>
  <strong>Student name:</strong>
  <%= @parent.student_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @parent.email %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @parent.teacher_id %>
</p>

<%= link_to 'Edit', edit_parent_path(@parent) %> |
<%= link_to 'Back', parents_path %>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h2>Editing Teacher</h2>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Listing Parents</h2>
<div>

<table class="modern", cellspacing="0">
  <caption align="top">
    <div align="left"><%= link_to 'New Parent', new_parent_path,class: "bordered-link" %></div>
  </caption>
  <thead>
    <tr class="border_bottom">
      <th>Name</th>
      <th>Email</th>
      <th>Student</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @parents.each do |parent| %>
      <tr class="border_bottom">
        <td><%= parent.name %></td>
        <td><%= parent.email %></td>
        <td><%= parent.student_name %></td>
        <td><%= @teacher.find_by_id(parent.teacher_id).name %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent), class: "bordered-link" %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' }, class: "bordered-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/teachers/new.html.erb
<h2>New Teacher</h2>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>